export default {
  // Auth
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  SPLASH: 'SPLASH',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  OTP: 'OTP',
  RESET_PASSWORD: 'RESET_PASSWORD',

  SCREEN1: 'SCREEN1',
  SCREEN2: 'SCREEN2',

  //Home
  HOME: 'HOME',

  //Settings
  SETTING: 'SETTING',
  PROFILE_SETTING: 'PROFILE_SETTING',

  //Find People
  FIND_PEOPLE: 'FIND_PEOPLE',
  SEARCH_PEOPLE: 'SEARCH_PEOPLE',

  //Profile
  PROFILE: 'PROFILE',
  VIEW_PROFILE: 'VIEW_PROFILE',
  USER_PROFILE: 'USER_PROFILE',

  //Promo Code
  PROMO_CODE: 'PROMO_CODE',

  //Bottom tab
  BOTTOM_TAB: 'BOTTOM_TAB',

  //Comments
  COMMENTS: 'COMMENTS',

  //Add post
  ADD_POST: 'ADD_POST',

  //Chat tab
  CHAT_TAB: 'CHAT_TAB',

  //New Chat
  NEW_CHAT: 'NEW_CHAT',

  //Create Group
  CREATE_GROUP: 'CREATE_GROUP',

  //Add Group Name
  ADD_GROUP_NAME: 'ADD_GROUP_NAME',

  //Gifted Chat
  GIFTED_CHAT: 'GIFTED_CHAT',
  GIFTED_GROUP_CHAT: 'GIFTED_GROUP_CHAT',

  //Likes Screen
  LIKES: 'LIKES',

  //Video Screen
  VIDEO: 'VIDEO',
};
