export default {
  // Auth
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  SPLASH: 'SPLASH',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  OTP: 'OTP',
  RESET_PASSWORD: 'RESET_PASSWORD',

  SCREEN1: 'SCREEN1',
  SCREEN2: 'SCREEN2',

  //Settings
  SETTING: 'SETTING',
  PROFILE_SETTING: 'PROFILE_SETTING',

  //Find People
  FIND_PEOPLE: 'FIND_PEOPLE',
  SEARCH_PEOPLE: 'SEARCH_PEOPLE',

  //Profile
  PROFILE: 'PROFILE',
  VIEW_PROFILE: 'VIEW_PROFILE',
  USER_PROFILE: 'USER_PROFILE',

  //Promo Code
  PROMO_CODE: 'PROMO_CODE',

  //Bottom tab
  BOTTOM_TAB: 'BOTTOM_TAB',
};
