require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
# install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'CasaVerse' do
  config = use_native_modules!
  # use_frameworks! :linkage => :static
  # Flags change depending on the env values.
  flags = get_default_flags()
#You may not need to use use_frameworks! or use_modular_headers! because it's getting conflict with use_flipper
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CasaVerseTests' do
    inherit! :complete
    
    # Pods for testing

  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
